function [timePs, THz] = importTHzFile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  REF1_SAMP1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a table.
%
%  REF1_SAMP1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  Ref1_Samp1 = importfile("C:\Users\chmoo\Documents\Research\Arbab Rotation\Mittleman\Ref1_Samp1.txt", [6, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 03-Mar-2026 13:23:19

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [6, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["timePs", "THz"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["timePs", "THz"], "ThousandsSeparator", ",");

% Import the data
outputData = readtable(filename, opts);

timePs = outputData.timePs;
THz = outputData.THz;

end